name: ci

on:
  workflow_dispatch:
  push:

jobs:
  bake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/bake-action@v6
        with:
          workdir: ./03-go-tessaract
          source: .
          files: ./docker-bake.hcl
          push: true
          sbom: false
          provenance: false
